Added token for point
bosagora/bizboa-bridge-contracts pull request #22
Opened 2022-05-13 02:20 UTC by Kang-Simon

2022-05-13 02:21 UTC, TrustHenry requested changes

2022-05-13 02:21 UTC, TrustHenry commented on contracts/swap/PointCoinSwap.sol
> +// contracts/swap/MetaSwap.sol
```suggestion
// contracts/swap/PointCoinSwap.sol
```

2022-05-13 02:21 UTC, TrustHenry commented on contracts/swap/PointTokenSwap.sol
> +// contracts/swap/MetaSwap.sol
```suggestion
// contracts/swap/PointTokenSwap.sol
```

2022-05-13 02:22 UTC, TrustHenry commented on contracts/swap/PointCoinSwap.sol
> +
```suggestion
```

2022-05-13 02:23 UTC, TrustHenry commented on contracts/swap/PointCoinSwap.sol
> +            liquidCoinBalance[swapFeeManagerAddress];
```suggestion
            liquidCoinBalance[_swapFeeManagerAddress] + liquidCoinBalance[swapFeeManagerAddress];
```

2022-05-13 02:26 UTC, TrustHenry commented on contracts/swap/PointCoinSwap.sol
> +        uint256 boa_amount = (_amount * BOA_UNIT_PER_COIN) / boaPrice;
정수로 완전히 나누어지지 않는 케이스를 보완 해야 할것입니다.

2022-05-13 02:45 UTC, Kang-Simon commented on contracts/swap/PointCoinSwap.sol
> +        uint256 boa_amount = (_amount * BOA_UNIT_PER_COIN) / boaPrice;
소수점 7자리 뒤로는 0으로 변경처리 했습니다.
```
boa_amount = (boa_amount / (10**11)) * (10**11);
```

2022-05-13 08:08 UTC, MichaelKim20 requested changes
일단 PointCoinSwap.sol을 마쳤습니다.

2022-05-13 08:08 UTC, MichaelKim20 commented on contracts/swap/PointCoinSwap.sol
> +        payable(msg.sender).transfer(sendAmount);
```suggestion
        IERC20 token = IERC20(pointAddress);
        require(_amount_point <= token.allowance(msg.sender, address(this)));
        require(token.transferFrom(msg.sender, address(this), _amount_point));

        uint256 swap_fee_point = calcSwapFee(_amount_point);
        uint256 send_amount_point = _amount_point - swap_fee_point;

        uint256 send_amount_boa = (send_amount_point * BOA_UNIT_PER_COIN) / boaPrice;
        require(send_amount_boa <= address(this).balance, "The coin liquidity is insufficient.");

        liquidTokenBalance[swapFeeManagerAddress] = liquidTokenBalance[swapFeeManagerAddress] + swap_fee_point;
        payable(msg.sender).transfer(send_amount_boa);
```

포인트를 코인으로 교환시 패킹되는 것은 포인트입니다. 확인해 주세요

2022-05-13 08:14 UTC, MichaelKim20 requested changes

2022-05-13 08:14 UTC, MichaelKim20 commented on contracts/swap/PointTokenSwap.sol
> +
token.burn(address(this), _amount);
를 넣어 토큰을 소각해야 되지 않나요?

2022-05-13 08:14 UTC, MichaelKim20 commented on contracts/swap/PointTokenSwap.sol
> +        token.transfer(msg.sender, tokenAmount);
```suggestion
        token.mint(msg.sender, tokenAmount);
```

마찬가지로 토큰을 발생하면 되지 않나요?

2022-05-13 08:15 UTC, MichaelKim20 commented on contracts/swap/PointTokenSwap.sol
> +        token.transfer(msg.sender, tokenAmount);
토큰의 유동성 공급기능이 없어서...

2022-05-13 08:16 UTC, MichaelKim20 commented on contracts/swap/PointCoinSwap.sol
> +        uint256 boa_amount = (_amount * BOA_UNIT_PER_COIN) / boaPrice;
계산결과 정수로 나오기 때문에 수정이 필요 없다고 생각합니다.

2022-05-16 05:19 UTC, Kang-Simon commented on contracts/swap/PointTokenSwap.sol
> +
burn / mint 로 변경했습니다.

2022-05-16 05:19 UTC, Kang-Simon commented on contracts/swap/PointTokenSwap.sol
> +        token.transfer(msg.sender, tokenAmount);
burn / mint 로 변경했습니다.

2022-05-16 05:29 UTC, MichaelKim20 approved these changes
LGTM

2022-05-16 05:42 UTC, merged